import { Box, Button, Grid, Paper, TextField, Typography } from "@mui/material"
import { Inter } from "next/font/google"
import Head from "next/head"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Template MUI y Next.js</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box
                    sx={{
                        maxWidth: 500,
                        p: 5,
                        bgcolor: "text.disabled"
                        // color: "text.primary"
                    }}
                >
                    asdffdsafas
                    <Paper
                        elevation={1}
                        sx={{
                            p: "32px",
                            display: "flex",
                            flexDirection: "column",
                            gap: 3
                        }}
                    >
                        <Typography sx={{ fontWeight: 500, fontSize: 24 }}>
                            Form
                        </Typography>

                        <Grid item xs={12}>
                            <TextField
                                id="outlined-basic"
                                label="Nombre"
                                variant="outlined"
                                sx={{ width: 1 }}
                            />
                        </Grid>

                        <Grid item xs={12}>
                            <TextField
                                id="outlined-basic"
                                label="Email"
                                variant="outlined"
                                sx={{ width: 1 }}
                            />
                        </Grid>

                        <Button variant="contained" sx={{ width: 1 }}>
                            Enviar
                        </Button>
                    </Paper>
                </Box>
            </main>
        </>
    )
}
